// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.js",
  },
  datasource: {
    // Prisma 7.2: Only 'url' and 'shadowDatabaseUrl' are supported in datasource config
    // url: Port 6543 + pgbouncer=true (for runtime queries via transaction pooler)
    // For migrations, Prisma will use DIRECT_URL if available via environment variable
    url: process.env["DATABASE_URL"],
    // Note: directUrl is not supported in prisma.config.ts for Prisma 7.2
    // Migrations will use DIRECT_URL from environment if available, otherwise DATABASE_URL
  },
});
