// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.js",
  },
  datasource: {
    // Prisma 7.2: Only 'url' and 'shadowDatabaseUrl' are supported in datasource config
    // IMPORTANT: Vercel doesn't support IPv6, so we MUST use pooler (6543) for both
    // - url: Pooler (Port 6543) - IPv4 accessible depuis Vercel - pour runtime queries ET migrations
    // - Direct connection (5432) uses IPv6 and won't work from Vercel
    // Solution: Set both DATABASE_URL and DIRECT_URL to pooler (6543) in Vercel
    url: process.env["DATABASE_URL"], // Pooler 6543 (IPv4) - utilisé pour queries ET migrations
  },
});
