// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.js",
  },
  datasource: {
    // Prisma 7.2: url and directUrl must be in prisma.config.ts, not schema.prisma
    // url: Port 6543 + pgbouncer=true (for runtime queries via transaction pooler)
    url: process.env["DATABASE_URL"],
    // directUrl: Port 5432 (for migrations via direct connection)
    directUrl: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
